kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: helloapp
  labels:
    {{- include "example-app.labels" . | nindent 4 }}
spec:
  strategy:
    type: Rolling
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - helloapp
        from:
          kind: ImageStreamTag
          name: 'helloapp:latest'
  replicas: {{ .Values.replicaCount }}
  selector:
    {{- include "example-app.selectorLabels" . | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "example-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: helloapp
          image: "helloapp:latest"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always